stages:
  data_ingestion:
    cmd: python data_ingestion.py
    deps:
    - data_ingestion.py
    - data
    outs:
    - splitted_data

  model_building:
    cmd: python model_trainer.py
    deps:
    - model_trainer.py
    - splitted_data
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python eval.py
    deps:
    - models/model.pkl
    - eval.py
    metrics:
    - metrics.json


